// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TEST_true.Models;

namespace TEST_true.Migrations
{
    [DbContext(typeof(TEST_true.Models.Database))]
    partial class DatabaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TEST_true.Models.comment", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("author");

                    b.Property<int?>("postID");

                    b.Property<int>("post_ID");

                    b.Property<string>("text");

                    b.HasKey("ID");

                    b.HasIndex("postID");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("TEST_true.Models.post", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("author");

                    b.Property<string>("name");

                    b.Property<string>("text");

                    b.HasKey("ID");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("TEST_true.Models.comment", b =>
                {
                    b.HasOne("TEST_true.Models.post")
                        .WithMany("List")
                        .HasForeignKey("postID");
                });
#pragma warning restore 612, 618
        }
    }
}
